// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class diy
{
        public const string leaderboard_diy_fashion = "CgkIsLDXtOMMEAIQAA"; // <GPGSID>
        public const string achievement_cut1 = "CgkIsLDXtOMMEAIQCg"; // <GPGSID>
        public const string achievement_cut2 = "CgkIsLDXtOMMEAIQCw"; // <GPGSID>
        public const string achievement_cut3 = "CgkIsLDXtOMMEAIQDA"; // <GPGSID>
        public const string achievement_pattern1 = "CgkIsLDXtOMMEAIQBw"; // <GPGSID>
        public const string achievement_pattern2 = "CgkIsLDXtOMMEAIQCA"; // <GPGSID>
        public const string achievement_pattern3 = "CgkIsLDXtOMMEAIQCQ"; // <GPGSID>
        public const string achievement_accessorize1 = "CgkIsLDXtOMMEAIQDQ"; // <GPGSID>
        public const string achievement_accessorize2 = "CgkIsLDXtOMMEAIQDg"; // <GPGSID>
        public const string achievement_accessorize3 = "CgkIsLDXtOMMEAIQDw"; // <GPGSID>
        public const string achievement_diyguru1 = "CgkIsLDXtOMMEAIQAQ"; // <GPGSID>
        public const string achievement_diyguru2 = "CgkIsLDXtOMMEAIQAg"; // <GPGSID>
        public const string achievement_diyguru3 = "CgkIsLDXtOMMEAIQAw"; // <GPGSID>
        public const string achievement_craftexper1 = "CgkIsLDXtOMMEAIQBA"; // <GPGSID>
        public const string achievement_craftexper2 = "CgkIsLDXtOMMEAIQBQ"; // <GPGSID>
        public const string achievement_craftexper3 = "CgkIsLDXtOMMEAIQBg"; // <GPGSID>

}

